Models/Brend.cs
namespace TurboazTask1.Models
{
    public class Brend
    {
        public int BrandId { get; set; }
        public string BrandName { get; set; }
    }
}

Models/Car.cs
namespace TurboazTask1.Models
{
    public class Car
    {

        public int CarId { get; set; }
        public string Name { get; set; }
        public double price { get; set; }
        public int year { get; set; }
        public int CarModelId { get; set; }

    }
}

Models/CarModel.cs
namespace TurboazTask1.Models
{
    public class CarModel
    {
        public int ModelId { get; set; }
        public string modelname { get; set; }

        public int BrendId { get; set; }

    }
}

Controllers/BrendController.cs
using Microsoft.AspNetCore.Mvc;
using TurboazTask1.Models;
using TurboazTask1.Services.Abstract;

namespace TurboazTask1.Controllers
{
    public class BrendController : Controller
    {
        private readonly IAppDataContext _context;

        public BrendController(IAppDataContext context)
        {
            _context = context;
        }
        public IActionResult Index()
        {
            return View(_context.Brends);
        }

        public IActionResult Detail(int id)
        {
            if(id==null) return BadRequest();

            List<CarModel> carmodels= _context.CarModels.FindAll(model => model.BrendId == id);

            if(carmodels==null) return NotFound();

            return View(carmodels);
        }
    }
}

Controllers/CarController.cs
using Microsoft.AspNetCore.Mvc;
using TurboazTask1.Models;
using TurboazTask1.Services.Abstract;

namespace TurboazTask1.Controllers
{
    public class CarController : Controller
    {
        private readonly IAppDataContext _context;

        public CarController(IAppDataContext context)
        {
            _context = context;
        }
        public IActionResult Index()
        {
            return View(_context.Cars);
        }

        public IActionResult Detail(int id)
        {

            if (id == null) return BadRequest();
           Car car= _context.Cars.Find(car=> car.CarId== id);
            if (car == null) return NotFound();
            return View(car);
        }
    }
}

Controllers/CarModelController.cs
using Microsoft.AspNetCore.Mvc;
using TurboazTask1.Models;
using TurboazTask1.Services.Abstract;

namespace TurboazTask1.Controllers
{
    public class CarModelController : Controller
    {
        private readonly IAppDataContext _context;

        public CarModelController(IAppDataContext context)
        {
            _context = context;
        }
        public IActionResult Index()
        {
            return View(_context.CarModels);
        }

        public IActionResult Detail(int id)
        {
            if (id == null) return BadRequest();

            List<Car> cars= _context.Cars.FindAll(car=>car.CarModelId==id);

            if(cars==null) return NotFound();

            return View(cars);

        }

    }
}

Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;

namespace TurboazTask1.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

Views/Brend/Detail.cshtml
@using TurboazTask1.Models;
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
@{
    ViewData["Title"] = "Detail";
}

@model List<CarModel>

<h1>Brends Detail</h1>

@foreach (CarModel carmodel in Model)
{
    <ul>

        <li>
            <a asp-controller="Carmodel" asp-action="Detail" asp-route-id="@carmodel.ModelId">@carmodel.modelname</a>
        </li>
    </ul>
}

Views/Brend/Index.cshtml
@using TurboazTask1.Models;
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers

@{
    ViewData["Title"] = "Index";
}

@model List<Brend>

<h1>Brend Page</h1>

@foreach (Brend brend in Model)
{
    <ul>
        <li>
            <a asp-controller="Brend" asp-action="Detail" asp-route-id="@brend.BrandId">@brend.BrandName</a>
        </li>
    </ul>
}

Views/Car/Detail.cshtml
@using TurboazTask1.Models

@{
    ViewData["Title"] = "Detail";
}

@model Car

<h1>Car Detail</h1>

<h3>Name: @Model.Name</h3>
<h3>Price: @Model.price</h3>
<h3>Year: @Model.year</h3>

Views/Car/Index.cshtml
@using TurboazTask1.Models;
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers

@{
    ViewData["Title"] = "Index";
}

@model List<Car>

<h1>Cars Page</h1>

@foreach (Car car in Model)
{
        <ul>
            <li>
                <a asp-controller="Car" asp-action="Detail" asp-route-id="@car.CarId"> CarName: @car.Name </a>
            </li>
        </ul>
}

Views/CarModel/Detail.cshtml
@using TurboazTask1.Models;
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
@{
    ViewData["Title"] = "Detail";
}

@model List<Car> 

<h1>Model Detail</h1>

@foreach (Car car in Model)
{
        <ul>

            <li>
                <a asp-controller="Car" asp-action="Detail" asp-route-id="@car.CarId">@car.Name</a>
            </li>
        </ul>
}

Views/CarModel/Index.cshtml
@using TurboazTask1.Models;
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers

@{
    ViewData["Title"] = "Index";
}

@model List<CarModel>

<h1>CarModels Page</h1>

@foreach (CarModel carmodel in Model)
{
        <ul>
            <li>
                <a asp-controller="Carmodel" asp-action="Detail" asp-route-id="@carmodel.ModelId">@carmodel.modelname</a>
            </li>
        </ul>
}

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Index";
}

<h1>Home Page</h1>

Views/Shared/_Layout.cshtml
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
</head>
<body>
    <div>
        <ul>
            <li>
                <a asp-controller="Home"  asp-action="Index">Home</a>
            </li>

            <li>
                <a asp-controller="Brend"  asp-action="Index">Car Brends</a>
            </li>

            <li>
                <a asp-controller="CarModel" asp-action="Index">Car Models</a>
            </li>

            <li>
                <a asp-controller="car" asp-action="Index">Cars</a>
            </li>
        </ul>
         
        @RenderBody()
    </div>
</body>
</html>